import requests
import os

class ValidationAPI:
   # function to declare api, url variables and doing the authorization
    def __init__(self, api_id, url):
        self.api_id = api_id
        self.url = url
        self.headers = {
            "Content-Type": "text/xml;charset=UTF-8",
            "SOAPAction": "urn:workflow#getWorkflow",
            "Authorization": api_id,
            "Content-Length": "287",
            "Host": "sesuiteqas.fgm.ind.br",
            "Connection": "Keep-Alive",
        }

    def get_workflow(self, process_id):
        soap_envelope = f"""<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:urn="urn:workflow">
                <soapenv:Header/>
                <soapenv:Body>
                    <urn:editEntityRecord>
                        <urn:WorkflowID>%RecordID%</urn:WorkflowID>
                        <urn:EntityID>dlc02</urn:EntityID>
                        <urn:EntityAttributeList>
                            <urn:EntityAttribute>
                            <urn:EntityAttributeID>nomcol</urn:EntityAttributeID>
                            <urn:EntityAttributeValue>%CurrentItem[0]%</urn:EntityAttributeValue>
                            </urn:EntityAttribute>
                            <urn:EntityAttribute>
                            <urn:EntityAttributeID>dataadmiss</urn:EntityAttributeID>
                            <urn:EntityAttributeValue>%Data1%</urn:EntityAttributeValue>
                            </urn:EntityAttribute>
                            <urn:EntityAttribute>
                            <urn:EntityAttributeID>datademiss</urn:EntityAttributeID>
                            <urn:EntityAttributeValue>%Data2%</urn:EntityAttributeValue>
                            </urn:EntityAttribute>
                            <urn:EntityAttribute>
                            <urn:EntityAttributeID>setor</urn:EntityAttributeID>
                            <urn:EntityAttributeValue>%CurrentItem[3]%</urn:EntityAttributeValue>
                            </urn:EntityAttribute>
                            <urn:EntityAttribute>
                            <urn:EntityAttributeID>cargo</urn:EntityAttributeID>
                            <urn:EntityAttributeValue>%CurrentItem[4]%</urn:EntityAttributeValue>
                            </urn:EntityAttribute>
                            <urn:EntityAttribute>
                            <urn:EntityAttributeID>motivodesliga</urn:EntityAttributeID>
                            <urn:EntityAttributeValue>%CurrentItem[6]%</urn:EntityAttributeValue>
                            </urn:EntityAttribute>
                            <urn:EntityAttribute>
                            <urn:EntityAttributeID>demaisconsi1</urn:EntityAttributeID>
                            <urn:EntityAttributeValue>%CurrentItem[8]%</urn:EntityAttributeValue>
                            </urn:EntityAttribute>
                            <urn:EntityAttribute>
                            <urn:EntityAttributeID>demaisconsi2</urn:EntityAttributeID>
                            <urn:EntityAttributeValue>%CurrentItem[10]%</urn:EntityAttributeValue>
                            </urn:EntityAttribute>
                            <urn:EntityAttribute>
                            <urn:EntityAttributeID>demaisconsi4</urn:EntityAttributeID>
                            <urn:EntityAttributeValue>%CurrentItem[12]%</urn:EntityAttributeValue>
                            </urn:EntityAttribute>
                            <urn:EntityAttribute>
                            <urn:EntityAttributeID>demaisconsid4</urn:EntityAttributeID>
                            <urn:EntityAttributeValue>%CurrentItem[14]%</urn:EntityAttributeValue>
                            </urn:EntityAttribute>
                            <urn:EntityAttribute>
                            <urn:EntityAttributeID>demaisconsi5</urn:EntityAttributeID>
                            <urn:EntityAttributeValue>%CurrentItem[27]%</urn:EntityAttributeValue>
                            </urn:EntityAttribute>
                            <urn:EntityAttribute>
                            <urn:EntityAttributeID>demaisconsi6</urn:EntityAttributeID>
                            <urn:EntityAttributeValue>%CurrentItem[29]%</urn:EntityAttributeValue>
                            </urn:EntityAttribute>
                            <urn:EntityAttribute>
                            <urn:EntityAttributeID>demaisconsi7</urn:EntityAttributeID>
                            <urn:EntityAttributeValue>%CurrentItem[31]%</urn:EntityAttributeValue>
                            </urn:EntityAttribute>
                            <urn:EntityAttribute>
                            <urn:EntityAttributeID>demaisconsi8</urn:EntityAttributeID>
                            <urn:EntityAttributeValue>%CurrentItem[33]%</urn:EntityAttributeValue>
                            </urn:EntityAttribute>
                            <urn:EntityAttribute>
                            <urn:EntityAttributeID>demaisconsi9</urn:EntityAttributeID>
                            <urn:EntityAttributeValue>%CurrentItem[43]%</urn:EntityAttributeValue>
                            </urn:EntityAttribute>
                            <urn:EntityAttribute>
                            <urn:EntityAttributeID>demaisconsi10</urn:EntityAttributeID>
                            <urn:EntityAttributeValue>%CurrentItem[45]%</urn:EntityAttributeValue>
                            </urn:EntityAttribute>
                            <urn:EntityAttribute>
                            <urn:EntityAttributeID>demaisconsi11</urn:EntityAttributeID>
                            <urn:EntityAttributeValue>%CurrentItem[47]%</urn:EntityAttributeValue>
                            </urn:EntityAttribute>
                            <urn:EntityAttribute>
                            <urn:EntityAttributeID>mensagemparafgm</urn:EntityAttributeID>
                            <urn:EntityAttributeValue>%CurrentItem[48]%</urn:EntityAttributeValue>
                            </urn:EntityAttribute>
                        </urn:EntityAttributeList>
                        <urn:RelationshipList>
                            <urn:Relationship>
                            <urn:RelationshipID>iniciativadesli</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>empregado</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[5]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>avaliacaojornad</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas1</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[7]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>avaliacaoestrut</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[9]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>avaliaambiente</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[11]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>avaambiente2</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[13]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>valtransp</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[15]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>valerefrest</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[16]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>plansaude</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[17]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>odontopl</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[18]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>farma</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[19]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>odonto</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[20]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>aniversario</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[21]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>casamento</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[22]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>nascimento</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[23]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>vacinagripe</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[24]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>segurovida</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[25]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>estudo</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[26]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>classificacao</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[28]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>avaliarecursos</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[30]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>avaliagestao</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[32]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>comunicacao</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[34]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>endomkt</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[35]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>treinamedesenvo</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[36]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>recruta</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[37]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>suportefolha</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[38]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>segurancatrab</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[39]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>ouvidoria</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[40]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>ccq</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[41]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>onboarding</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[42]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>voltariatrab</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[44]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                            <urn:Relationship>
                            <urn:RelationshipID>indicafgm</urn:RelationshipID>
                            <urn:RelationshipAttribute>
                                <urn:RelationshipAttributeID>escolhas</urn:RelationshipAttributeID>
                                <urn:RelationshipAttributeValue>%CurrentItem[46]%</urn:RelationshipAttributeValue>
                            </urn:RelationshipAttribute>
                            </urn:Relationship>
                        </urn:RelationshipList>
                    </urn:editEntityRecord>
                </soapenv:Body>
                </soapenv:Envelope>"""